import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/providers/app-providers";

export const metadata: Metadata = {
  title: "Veritas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='antialiased'>
      <body className='min-h-full flex flex-col'>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
